name: 'xlsx-to-csv-action'
description:
  'Convert xlsx file to csv file, with the ability to filter / rename columns'
author: 'Joe Siu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  inputFile:
    description: 'Input xlsx file path'
    required: true
  outputDir:
    description: 'Output directory'
    required: true
    default: './'
  filter:
    description:
      'Filter columns in JSON format, e.g., {"Column 1": "column1", "Column 2":
      "column2"}'
    required: false

# Define your outputs here.
outputs:
  outputFile:
    description: 'Output csv file path'

runs:
  using: node20
  main: dist/index.js
