name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  inputFile:
    description: 'Input xlsx file'
    required: true
  outputDir:
    description: 'Output directory'
    required: true
    default: './'
  filter:
    description: 'Filter columns in JSON format, e.g., {"Column 1": "column1", "Column 2": "column2"}'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
