name: 'xlsx-to-csv-action'
description:
  'Convert xlsx file to csv file, with the ability to filter / rename columns'
author: 'Joe Siu'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'gray-dark'

# Define your inputs here.
inputs:
  inputFile:
    description: 'Input file path, must be a `.xlsx` file'
    required: true
  outputDir:
    description: 'Output directory'
    required: true
    default: './'
  outputFilename:
    description: 'Output filename'
    required: false
  filter:
    description:
      'A JSON string of the columns to filter and rename
e.g., `{ "Segment": "segment", "Country": "country" }`'
    required: false

# Define your outputs here.
outputs:
  outputFile:
    description: 'Output csv file path'

runs:
  using: node20
  main: dist/index.js
